#!/usr/bin/env python

from clustering import *

description="""\
Filter repeats by linkage-based clustering.
"""
usage="%prog file1.ydat file2.ydat ... "

default_chi2 = 2.2


def main():
    oprs = OptionParser(usage=usage, description=description)
    oprs.add_option("-c", "--chisq-threshold",
        action="store", type="float", dest="threshold", default=default_chi2,
        help="chi-squared threshold for cluster splitting. Default is %3g" % default_chi2)
    oprs.add_option("-n", "--noplot",
        action="store_false", dest="plot", default=True,
        help="Do not plot results for each repetition.")
    (opts, args) = oprs.parse_args()
    if len(args) < 1:
        oprs.error("One or more input files needed.")
    average_positions(args, chi2cutoff=opts.threshold, write=1, plot=opts.plot)


if __name__ == "__main__":
    main()
