#!/usr/bin/python

import sys, re
import numpy as np
import matplotlib.pyplot as plt
from optparse import OptionParser
from yamlformats import read_ydat
from atsasformats import write_dat


description="Convert YAML-dat format to dat."

usage="%prog [-o <output.dat>] <file.yaml>"


def write_yaml2dat(inname, outname, threecols=False):
    dat = read_ydat(inname)
    if threecols:
        dat = dat[0:3,:]
    write_dat(dat, outname, comment=inname)

def main():
    oprs = OptionParser(usage=usage, description=description)
    oprs.add_option("-o", "--output",
        action="store", type="string", dest="outfile", default=None,
        help="The output file name. Only one file can be converted if this option is given. The default is to use input file name with the extension '.dat' as the output file name.")
    oprs.add_option("-3", "--three-columns",
        action="store_true", dest="threecols", default=False,
        help="Only write 3 columns to the output file, even if the input has more.")
    (opts, args) = oprs.parse_args()
    if len(args) < 1:
        oprs.error("Missing input file name(s).")
    if opts.outfile is not None and len(args) != 1:
        oprs.error("Only one input argument can be given with explicit output file name.")

    if opts.outfile is not None:
        write_yaml2dat(args[0], opts.outfile, opts.threecols)
    else:
        for inname in args:
            if inname.endswith('.dat'):
                oprs.error("Input file ending with '.dat'. Refusing to continue.")
            outname = re.sub(r'\.[^\. ]*$', '.dat', os.path.basename(inname))
            write_yaml2dat(inname, outname, opts.threecols)


if __name__ == "__main__":
    main()

